---
name: 'Build and push images'

# https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/
# https://github.com/ahmetozer/github-actions-multi-arch-container-ghcr.io
# https://github.com/docker/login-action

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up BuildX
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        id: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dig-short:latest
