---
name: 'Build and test'

on:
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Build and test
        id: build
        run: |
          docker build --tag local/dig-short:test .
          docker run --rm local/dig-short:test 1dot1dot1dot1.cloudflare-dns.com | grep 1.1.1.1
